### ISSUE TITLE
Reformatting package side of code

### ISSUE THREAD

**Issue by JamesPino** [sgosline/mpnstXenoModeling#53]
Mainly putting here for a reminder for discussion points.  I have been going through the repo and just going to put some notes and goals.

1. Cleaning up code. 
Reading up on R packages, I found this little note.

> Don’t use library() or require(). These modify the search path, affecting what functions are available from the global environment. Instead, you should use the DESCRIPTION to specify your package’s requirements, as described in chapter 8. This also makes sure those packages are installed when your package is installed.

  (found at https://r-pkgs.org/r.html,  chapter 7.5).  
Should we stick to R packaging guidelines? This prevents overrides like   `1: replacing previous import 'dplyr::combine' by 'gridExtra::combine' when loading 'mpnstXenoModeling'`
It might also clean up the markdowns, where all those packages will be installed when we install the package via the DESCRIPTION.

it also addresses the warnings in the github actions (https://github.com/sgosline/mpnstXenoModeling/runs/4538089629?check_suite_focus=true) . 
>  Please use :: or requireNamespace() instead. 

I don't mind making the adjustments once I get a hang of the tests, but mainly wanted to know everyone's thoughts on using such guidelines.  I don't think it will require a lot of work.

**Comment by sgosline** [comment]
This is all good - but the moving the synapse install inside the package is breaking the github action. I tried to debug but it seems challenging. have you seen any examples?  This is the only one i foudn: https://github.com/rstudio/reticulate/issues/999

**Comment by sgosline** [comment]
I think i fixed this
